## 1. Импорт библиотек и настройка параметров

In [2]:
# Импортируем библиотеки:

import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import requests
import time
import os
import re
from datetime import datetime
from sklearn.feature_selection import f_classif, mutual_info_classif
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler

%matplotlib inline

In [3]:
# Увеличиваем число отображаемых строк и столбцов в pandas:

pd.set_option('display.max_rows', 50)
pd.set_option('display.max_columns', 50)
pd.set_option('display.width', 1000)

In [4]:
# Задаем дирректорию для работы с файлами:

# При выполнении на kaggle раскомментировать этот блок:
# for dirname, _, filenames in os.walk('/kaggle/input'):
#    for filename in filenames:
#        print(os.path.join(dirname, filename))
# PATH_to_file = '/kaggle/input/sf-dst-scoring/'

# При выполнении локально раскомментировать этот блок:
for dirname, _, filenames in os.walk('./data'):
    for filename in filenames:
        print(os.path.join(dirname, filename))
PATH_to_file = './data/'

./data/cars_dicts.txt
./data/.DS_Store
./data/not_read_links.txt
./data/car_links.txt
./data/test.csv
./data/df_prepared.csv
./data/train.csv
./data/test_finished.csv
./data/pages_count_list.txt
./data/sample_submission.csv

In [5]:
# Фиксируем параметры для воспроизводимости экспериментов:

RANDOM_SEED = 42
!pip freeze > requirements.txt
CURRENT_DATE = pd.to_datetime('17/07/2021')

## 2. Подготовка данных

### 2.1 Загрузка датасета

In [7]:
# Загрузим подготовленный датасет:

df = pd.read_csv(PATH_to_file + 'df_prepared.csv')

print('Размер датасета: ', df.shape)
display(df.sample(5))

Размер датасета:  (126689, 38)

        body_type  brand  color  engine_power  fuel_type  mileage  model_name  doors_num  production_date  transmission  vendor  owners_count  docs  drive  steering      price  test  pop_color  pop_brand  elite_brand  pop_model  prod_annot  km_year  rarity  desc_digits  desc_len  options_count  airbag-passenger  aux  electro-mirrors  electro-window-back  esp  front-seats-heat  immo  mirrors-heat  other  ptf  usb
106033          0     22     15           170          0   228000         808          3             2009             1       0             2     1      0         0  13.567049     0          1          1            0          1           2    19000       0            5       389              0               0.0  0.0              0.0                  0.0  0.0               0.0   0.0           0.0    0.0  0.0  0.0
125163          9     21      1           280          3   208000         523          2             1996             1       1             1     1      2         1  12.994530     0          1          1            0          1           0     8320       0            2       109              0               0.0  0.0              0.0                  0.0  0.0               0.0   0.0           0.0    0.0  0.0  0.0
100488          5      0      1           326          0    62000         105          3             2016             0       0             0     1      0         0  15.088076     0          1          1            1          1           2    12400       0            8      1179             60               1.0  0.0              1.0                  1.0  1.0               1.0   1.0           1.0    1.0  0.0  1.0
23702           0     22     15           150          3    13000         808          3             2019             2       0             0     1      0         0   0.000000     1          1          1            0          1           3     6500       0            6      1070             14               1.0  0.0              0.0                  0.0  0.0               0.0   0.0           0.0    1.0  0.0  0.0
114464         12     15      7           136          0   146000          46          3             2008             0       0             1     1      1         0  13.102161     0          0          0            0          1           1    11231       0            0       193              0               0.0  0.0              0.0                  0.0  0.0               0.0   0.0           0.0    0.0  0.0  0.0

In [21]:
# Разделим датасет на тестовый (для которого будем предсказывать цены)
# и тренировочный, на котором будем тренировать модель:

df_test = df[df.test == 1]

df_train = df[df.test == 0]

In [22]:
# Удалим признак test из обоих датасетов. Из тестового датасета так-же
# удалим признак price, который нам надо будет предсказать:

df_test = df_test.drop(columns = ['test', 'price'], axis = 1)

df_train = df_train.drop(columns = 'test', axis = 1)